apiVersion: v1
kind: Pod
metadata:
  name: busy
  labels:
    app: busy
spec:
  containers:
    - name: busy
      image: busybox:1.36
      imagePullPolicy: IfNotPresent
      command: ["sleep", "10d"]
      volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: ghost-content
  volumes:
    - name: ghost-content
      persistentVolumeClaim:
        claimName: "ghost-ghost-content-claim"
  restartPolicy: Always
  