ghost:
  nodeEnv: development

service:
  type: ClusterIP
  port: 80

container:
  image:
    repository: ghost
    tag: 5.44.0-alpine
    pullPolicy: IfNotPresent

database:
  client: sqlite
  connection:
    filename: /var/lib/ghost/content/data/ghost.db
    mount: /var/lib/ghost/content/data
