ghost:
  nodeEnv: development
  timezone: UTC
  url: https://themisha.dev
  storage: 1Gi
  image:
    repository: ghost
    tag: 5.44.0-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  mail:
    from: "themisha.dev <"
    transport: SMTP
    host: smtp.gmail.com
    port: 587
    auth:
      privateSecretRef: ghost-mail

mysql:
  size: 8Gi
  image:
    repository: mysql
    tag: 8.0.33-debian
    pullPolicy: IfNotPresent
  connection:
    # mysql-database
    # mysql-username
    # mysql-password
    # mysql-root-password
    privateSecretRef: ghost-mysql
  mount: /var/lib/mysql

# backup configuration via cronjob
backup:
  enabled: false
  awsSecretRef: ghost-backup
  schedule: "* * * * *"
  retentionDays: 7
  ttlSecondsAfterFinished: 86400
  mysqlPath: "ghost/backup/mysql"
  ghostPath: "ghost/backup/ghost"
