apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.container.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{- .Values.container.image -}}:{{- .Values.container.imageTag -}}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.container.port | int }}
          protocol: TCP
        resources:
          {{ toYaml .Values.resources | indent 10 }}