apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-gpt.container.name" . | quote }}
spec:
  selector:
    matchLabels:
      app: {{ include "chat-gpt.container.name" . | quote }}
  template:
    metadata:
      labels:
        app: {{ include "chat-gpt.container.name" . | quote }}
    spec:
      containers:
        - name: {{ include "chat-gpt.container.name" . | quote }}
          image: {{ include "chat-gpt.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ include "chat-gpt.container.port" . | int }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}