apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-gpt
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: chat-gpt
  replicas: {{ default 1 .Values.container.replicaCount | int }}
  template:
    metadata:
      labels:
        app: chat-gpt
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{- .Values.container.image -}}:{{- .Values.container.imageTag -}}
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port | int }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}