apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-gpt.service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "chat-gpt.container.name" . }}