apiVersion: v1
kind: Service
metadata:
  name: chat-gpt
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: chat-gpt