{{ if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup-cronjob
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.backup.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: upload-backup
              image: {{ include "backup.image" . }}
              env:
                - name: S3_REGION
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.awsSecretRef }}
                      key: S3_REGION
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.awsSecretRef }}
                      key: S3_BUCKET
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.awsSecretRef }}
                      key: S3_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.awsSecretRef }}
                      key: S3_SECRET_ACCESS_KEY
                - name: MYSQL_HOST
                  value: {{ include "mysql.host" . | quote }}
                - name: MYSQL_USER
                  value: "root"
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.mysql.connection.privateSecretRef }}
                      key: mysql-root-password
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.mysql.connection.privateSecretRef }}
                      key: mysql-database
                - name: RETENTION_DAYS
                  value: "{{ .Values.backup.retentionDays }}"
                - name: BACKUP_PATH
                  value: "{{ .Values.backup.backupPath }}"
                - name: DIRS_TO_BACKUP
                  value: "{{ .Values.ghost.mount }}"
              volumeMounts:
                - mountPath: {{ .Values.ghost.mount }}
                  name: ghost-content
          volumes:
            - name: ghost-content
              persistentVolumeClaim:
                claimName: "{{ .Release.Name }}-ghost-volume-claim"
{{ end }}