---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
spec:
  storageClassName: {{ .Release.Name }}-local-storage
  capacity:
    storage: {{ .Values.database.size }}
  local:
    path: {{ .Values.database.connection.mount }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: {{ .Release.Name }}-litestream-restore
          image: "{{ include "litestream.image" . }}"
          args:
            - "restore"
            - "-if-not-exists"
            - "-if-replica-exists"
            - "-v"
            - "-o"
            - "{{ .Values.database.connection.filename }}"
            - "{{ include "litestream.s3.path" . }}"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.litestream.awsSecretRef }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.litestream.awsSecretRef }}
                  key: aws_secret_access_key
          volumeMounts:
            - mountPath: {{ .Values.database.connection.mount }}
              {{ .Release.Name }}-volume-claim

      containers:
        - name: {{ .Release.Name }}
          image: "{{ include "ghost.image" . }}"
          imagePullPolicy: {{ .Values.ghost.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.database.connection.mount }}
              name: {{ .Release.Name }}-volume-claim
          ports:
            - containerPort: 2368
              name: http
          env:
            - name: database__client
              value: {{ .Values.database.client }}
            - name: NODE_ENV
              value: {{ .Values.ghost.nodeEnv }}
              {{ if eq .Values.database.client "sqlite3" }}
            - name: database__connection__filename
              value: {{ .Values.database.connection.filename }}
              {{ end }}
            - name: TZ
              value: {{ .Values.ghost.timezone }}
            - name: url
              value: {{ .Values.ghost.url }}

        # sidecar litestream that replicates everything to S3 in the background
        - name: {{ .Release.Name }}-litestream
          image: "{{ include "litestream.image" . }}"
          args:
            - "replicate"
            - "{{ .Values.database.connection.filename }}"
            - "{{ include "litestream.s3.path" . }}"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.litestream.awsSecretRef }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.litestream.awsSecretRef }}
                  key: aws_secret_access_key
          volumeMounts:
            - mountPath: {{ .Values.database.connection.mount }}
              name: {{ .Release.Name }}-volume-claim
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-volume-claim
      spec:
        storageClassName: {{ .Release.Name }}-local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.database.size }}