apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ghost.fullName" .}}
  template:
    metadata:
      labels:
        app: {{ include "ghost.fullName" .}}
    spec:
      initContainers:
        - name: mysql-wait
          image: busybox:1.36.0
          env:
            - name: MYSQL_HOST
              value: {{ include "mysql.host" . | quote }}
            - name: MYSQL_PORT
              value: "3306"
          command:
            - sh
            - -c
            - |
              #!/bin/sh
              until echo "SELECT 1" | nc -w 1 ${MYSQL_HOST} ${MYSQL_PORT}>/dev/null; do
                echo "MySQL is not running yet"
                sleep 1
              done

              echo "MySQL is running"
        - name: ghost-apply-backup
          image: {{ include "backup.image" . }}
          command:
            - ./scripts/apply-backup.sh
          env:
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.awsSecretRef }}
                  key: S3_REGION
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.awsSecretRef }}
                  key: S3_BUCKET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.awsSecretRef }}
                  key: S3_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.awsSecretRef }}
                  key: S3_SECRET_ACCESS_KEY
            - name: MYSQL_HOST
              value: {{ include "mysql.host" . | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-database
            - name: BACKUP_PATH
              value: {{ .Values.backup.backupPath }}
            - name: GHOST_PATH
              value: {{ .Values.ghost.mount }}

          volumeMounts:
            - mountPath: {{ .Values.ghost.mount }}/content
              name: ghost-content
            - mountPath: {{ .Values.ghost.mount }}/current
              name: ghost-current
      containers:
        # Ghost
        - name: {{ .Release.Name }}
          image: "{{ include "ghost.image" . }}"
          imagePullPolicy: {{ .Values.ghost.image.pullPolicy }}
          ports:
            - containerPort: 2368
              name: http
          env:
            - name: NODE_ENV
              value: {{ .Values.ghost.nodeEnv | quote }}
            - name: TZ
              value: {{ .Values.ghost.timezone | quote }}
            - name: url
              value: {{ .Values.ghost.url | quote }}
            - name: mail__from
              value: {{ .Values.ghost.mail.from | quote }}
            - name: mail__transport
              value: {{ .Values.ghost.mail.transport | quote }}
            - name: mail__options__host
              value: {{ .Values.ghost.mail.host | quote }}
            - name: mail__options__port
              value: {{ .Values.ghost.mail.port | quote }}
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.mail.auth.privateSecretRef }}
                  key: username
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.mail.auth.privateSecretRef }}
                  key: password
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: {{ include "mysql.host" . | quote }}
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-password
            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-database
          volumeMounts:
            - mountPath: {{ .Values.ghost.mount }}/content
              name: ghost-content
            - mountPath: {{ .Values.ghost.mount }}/current
              name: ghost-current
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-ghost-content-claim"
        - name: ghost-current
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-ghost-current-claim"
