apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-ghost-volume"
spec:
  capacity:
    storage: {{ .Values.ghost.storage }}
  local:
    path: {{ .Values.ghost.mount }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ghost-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.ghost.storage }}
