apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  serviceName: {{ .Release.Name }}-mysql
  template:
    metadata:
      name: {{ .Release.Name }}-mysql
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
        - name: {{ .Release.Name }}-mysql
          image: "{{ include "mysql.image" . }}"
{{/*          livenessProbe:*/}}
{{/*            exec:*/}}
{{/*              command: [ "mysqladmin", "ping" ]*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 10*/}}
{{/*            timeoutSeconds: 5*/}}
{{/*          readinessProbe:*/}}
{{/*            exec:*/}}
{{/*              command: [ "mysqladmin", "ping" ]*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 10*/}}
{{/*            timeoutSeconds: 5*/}}
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.connection.privateSecretRef }}
                  key: mysql-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: {{ .Values.mysql.mount }}
              name: {{ .Release.Name }}-sql-claim
      volumes:
        - name: {{ .Release.Name }}-sql-claim
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-sql-claim
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-sql-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mysql.size }}