name: Release Charts

on:
  push:
    paths: 
      - 'charts/**'
      - '.github/workflows/release-charts.yml'
    branches:
      - main

permissions:
  contents: write # write releases
  id-token: write
  packages: write # write packages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ghost:
              - 'charts/ghost/**'

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart to GHCR
        if: steps.changes.outputs.ghost == 'true'
        run: |
          helm package charts/ghost
          helm push ghost-*.tgz oci://ghcr.io/hawkkiller/charts